version: '3'

services:
  web:
    build: .
    command: daphne appchatss.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6380:6379"
