version: '3'

services:
  web:
    build: .
    command: daphne mysite.routing.application -b 0.0.0.0 -p 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
