# Generated by Django 3.2.12 on 2022-03-24 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_testmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherreceiver1', to=settings.AUTH_USER_MODEL)),
                ('otherSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otheruser1', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
