# Generated by Django 3.2.12 on 2022-03-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_testmessage1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMessage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('testMessage1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='chat.testmessage1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
