# Generated by Django 3.2.12 on 2022-04-02 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_testmessage3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firnd_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
